### ISSUE TITLE
Support for Quizzet on mobile browsers

### ISSUE THREAD

**Issue by kshitij86** [PragatiVerma18/MLH-Quizzet#3]
**Describe the bug**
The app seems to crash after uploading the document when accessed from a mobile device.

**To Reproduce**
1. Go to `http://localhost:5000/` on a mobile browser.
2. Upload a document and click 'Submit'.
3. Quizzet should crash and not present the quiz screen.

**Expected behavior**
MLH Quizzet should work on mobile phones as it works on a computer.

**Smartphone (please complete the following information):**
 - Device: One Plus 3T
 - OS: Android 6.0 (Marshmallow)
 - Browser: Firefox

**Comment by PragatiVerma18** [comment]
https://github.com/PragatiVerma18/MLH-Quizzet/issues/3

**Comment by PragatiVerma18** [comment]
https://medium.com/python-pandemonium/building-and-deploying-an-enterprise-django-web-app-in-16-hours-79e018f7b94c

<blockquote><img src="https://miro.medium.com/max/1200/1*Lia3TmBCU1cJuU0k4OtU1g.png" width="48" align="right"><div><img src="https://miro.medium.com/1*m-R_BkNf1Qjr1YbyOIJY2w.png" height="14"> Medium</div><div><strong><a href="https://medium.com/python-pandemonium/building-and-deploying-an-enterprise-django-web-app-in-16-hours-79e018f7b94c">Building and deploying an Enterprise Django Web App in 16 hours</a></strong></div><div>A week ago I put together an application for internal employees to be recognised for learning achievements and share them with their…</div></blockquote>
